### ISSUE TITLE
Plugin documentation link dead

### ISSUE THREAD

**Issue by qguv** [revspace/revbank#13]
Hey, the [plugin documentation link](https://metacpan.org/pod/RevBank::Plugins) in the README appears dead.

**Comment by RevBar** [comment]
Quint Guvernator skribis 2020-10-10  3:09 (-0700):
> Hey, the [plugin documentation link](https://metacpan.org/pod/RevBank::Plugins) in the README appears dead.

Unfortunately the POD to markdown conversion does that, based on the
wrong assumption that every Perl library is hosted on CPAN.

There is no easy fix other than to switch to Markdown for the source
format.

A working link would be
https://github.com/revspace/revbank/blob/master/lib/RevBank/Plugins.pod
but note that Github's rendering has the exact same bug, and that the
link to RevBank::Global is equally broken.

**Comment by qguv** [comment]
Thanks for the link!
