### ISSUE TITLE
issue with iban qr code generating

### ISSUE THREAD

**Issue by TheMrCaveman** [revspace/revbank#16]
Hi, 

I set up a new revbank and setup the qr code plugin with the correct information. 
And followed the UTF-8 guide. Now is I want to use the iban payment it gives me the error 
Plugin 'users' failed: open2: exec of qrencode -t ansiutf8 -m 2 failed : No sucht file or directory at plugins/deposit_iban_qr line 32., called at /home/pi/revbank/lib/revbank/Cart.pm line 98.

Any idea what I miss here?

**Comment by Juerd** [comment]
The qr plugin uses an external program `qrencode`. Can you check if you have that installed?
